server:
  port: 1995
  ipAddress: "44.114.12.43"
  extraPort: 1996
  localImplementPath: /srv/nfsroot/

project:
  projectNum: 13
  projectName: SZBridge
  projectStartStakeMark: K0+000


radarTypeVec:
  - typeNum:  1
    isTunnel:  0
    incomingLaneNum:  0
    outgoingLaneNum:  2
    startIncoming:  2 
    startOutgoing:  2
    radarDirection: 1
  - typeNum:  2
    isTunnel:  0
    incomingLaneNum:  0
    outgoingLaneNum:  2
    startIncoming:  2 
    startOutgoing:  2
    radarDirection: 0
  - typeNum:  3
    isTunnel:  1
    incomingLaneNum:  0
    outgoingLaneNum:  3
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum:  4
    isTunnel:  0
    incomingLaneNum:  3
    outgoingLaneNum:  3
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum:  5
    isTunnel:  0
    incomingLaneNum:  3
    outgoingLaneNum:  3
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0
  - typeNum:  6
    isTunnel:  0
    incomingLaneNum:  2
    outgoingLaneNum:  0
    startIncoming:  2 
    startOutgoing:  2
    radarDirection: 1
  - typeNum:  7
    isTunnel:  0
    incomingLaneNum:  2
    outgoingLaneNum:  0
    startIncoming:  2 
    startOutgoing:  2
    radarDirection: 0
  - typeNum:  8
    isTunnel:  1
    incomingLaneNum:  0
    outgoingLaneNum:  3
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0
  - typeNum:  9
    isTunnel:  1
    incomingLaneNum:  3
    outgoingLaneNum:  0
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum: 10
    isTunnel:  0
    incomingLaneNum:  0
    outgoingLaneNum:  3
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0
  - typeNum: 11
    isTunnel:  0
    incomingLaneNum:  3
    outgoingLaneNum:  0
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0
  - typeNum: 12
    isTunnel:  0
    incomingLaneNum:  0
    outgoingLaneNum:  3
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum: 13
    isTunnel:  0
    incomingLaneNum:  3
    outgoingLaneNum:  0
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum: 14
    isTunnel:  0
    incomingLaneNum:  4
    outgoingLaneNum:  4
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum: 15
    isTunnel:  0
    incomingLaneNum:  4
    outgoingLaneNum:  4
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0
  - typeNum: 16
    isTunnel:  0
    incomingLaneNum:  4
    outgoingLaneNum:  4
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0
  - typeNum: 17
    isTunnel:  0
    incomingLaneNum:  4
    outgoingLaneNum:  4
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum: 18
    isTunnel:  1
    incomingLaneNum:  0
    outgoingLaneNum:  4
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 1
  - typeNum: 19
    isTunnel:  1
    incomingLaneNum:  0
    outgoingLaneNum:  4
    startIncoming:  1
    startOutgoing:  1
    radarDirection: 0